name: Build echo-server from master

on:
  push:
    branches: [ master ]

  workflow_dispatch:
    inputs:
      docker-tag:
        description: "Tag for image push"
        default: latest
        required: true

env:
  DEFAULT_TAG: latest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Commit
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set default docker tag for builds from master
        id: docker-tag
        run: |
          USER_INPUT="${{ github.event.inputs.docker-tag }}"
          echo "value=${USER_INPUT:-$DEFAULT_TAG}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: docker/
          push: true
          tags: rafalskolasinski/gha-echo-server:${{ steps.docker-tag.outputs.value }}
