name: Dispatch Echo

on:

  push:
    branches: [ master ]

  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World!'
        required: true

env:
  DEFAULT_NAME: World!

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
    - name: Set default name of person to greet
      id: set-name
      run: |
        USER_INPUT="${{ github.event.inputs.echo }}"
        echo "value=${USER_INPUT:-$DEFAULT_NAME}" >> $GITHUB_OUTPUT

    - name: Send the greeting
      run: |
        echo "Hello ${{ steps.set-name.outputs.value }}"
