name: Matrix Build

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  matrix:
    name: Job for ${{ matrix.person }} - ${{ matrix.fruit }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fruit: [apple, pear]
        person: [Tom, John]

    steps:
    - name: ${{ matrix.person }}'s fruit preference
      run: |
        echo "${{ matrix.person }} likes ${{ matrix.fruit }}"
